config/routes.rb
Younifier::Application.routes.draw do

  root :to => 'welcome#index'

  get '/auth/:provider/callback', to: "sessions#create"
  get '/auth/failure', to: redirect('/')
  get '/signout', to: 'sessions#destroy', as: 'signout'

  get '/auth/twitter/callback', to: "sessions#twitter"

  get '/mail', :to => "mail#form"
  post '/send_email', :to => "mail#send_email"

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid, :img_url, :location

  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  		user.provider = auth.provider
  		user.uid = auth.uid
  		user.name = auth.info.name
  		user.oauth_token = auth.credentials.oauth_token
  		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  		user.save!
  	end
  end

  has_many :providers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/mail_controller.rb
class MailController < ApplicationController
	def form
	end

	def send_email
		@to = params[:to]
		@subject = params[:subject]
		Mailer.form_email(@to, @subject, params[:body]).deliver
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def twitter
		# render :json => request.env['omniauth.auth'].to_json
		session[:twitter_token] = auth_hash['credentials']['token']
		session[:twitter_secret] = auth_hash['credentials']['secret']
		@username = auth_hash['info']['nickname']
		@name = auth_hash['info']['name']
		@location = auth_hash['info']['location']
		@img_url = auth_hash['info']['image']
		@description = auth_hash['info']['description']
	end

	# def facebook
	# 	#render :json => auth_hash.to_json
	# 	session[:facebook_token] = auth_hash['credentials']['token']
	# 	session[:facebook_secret] = auth_hash['credentials']['secret']
	# 	@username = auth_hash['info']['nickname']
	# 	@name = auth_hash['info']['name']
	# 	@location = auth_hash['info']['location']
	# 	@img_url = auth_hash['info']['image']
	# 	@description = auth_hash['info']['description'] 
	# 	token = auth_hash["credentials"]["token"]
	# 	@graph = Koala::Facebook::API.new(token)
	# 	@friends = @graph.get_connections("me", "friends")
	# end

	def create
		@user = User.from_omniauth(env["omniauth.auth"])
		session[:user_id] = @user.id
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end


	private

	def auth_hash
		request.env['omniauth.auth']
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Younifier</title>
  <%= stylesheet_link_tag	"application", :media => "all" %>
  <%= stylesheet_link_tag	"unsemantic-grid-base", "unsemantic-grid-desktop", "unsemantic-grid-mobile", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="user_nav">
		<% if current_user %>
		Signed in as <%= current_user.name %>!
			<%= link_to "Sign out", signout_path %>
		<% else %>
			<%= link_to "Sign in with Facebook", "auth/facebook", id: "sign_in" %>
		<% end %>
	</div>


<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="grid-35">Facebook<br/>
	<a href="/auth/facebook">
		<img src="http://media3.vindy.com/ellington_defaults/images/avatars/blank_avatar_240x240.gif" alt="facebook sign-in">
	</a>
</div>

<div class="grid-35"> Twitter <br/>
	<a href="/auth/twitter">
		<img src="http://media3.vindy.com/ellington_defaults/images/avatars/blank_avatar_240x240.gif" alt="twitter sign-in">
	</a>
</div>